FROM openjdk:11
MAINTAINER Shreyas Deshpande <shreyas.deshpande26@gmail.com>
ADD target/vaadin-project-0.0.1-SNAPSHOT.jar vaadin-project-0.0.1-SNAPSHOT.jar
EXPOSE 8080:8080
ENTRYPOINT ["java","-jar","vaadin-project-0.0.1-SNAPSHOT.jar"]